apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: containerd-goroutine-collector
spec:
  processor:
    httpServer:
      path: /processor/containerdGoroutineCollector
      scheme: http
    timeoutSeconds: 60
