apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: container-collector
spec:
  processor:
    httpServer:
      path: /processor/containerCollector
      scheme: http
    timeoutSeconds: 60
