apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: core-file-profiler
spec:
  processor:
    httpServer:
      path: /processor/coreFileProfiler
      scheme: http
    timeoutSeconds: 60