apiVersion: diagnosis.kubediag.org/v1
kind: Operation
metadata:
  name: node-cordon
spec:
  processor:
    httpServer:
      path: /processor/nodeCordon
      scheme: http
    timeoutSeconds: 60
