apiVersion: v1
kind: Pod
metadata:
  name: http-operation
  namespace: kubediag
  labels:
    operation: cache
    type: http
spec:
  containers:
  - name: http-operation
    image: hub.c.163.com/kubediag/http-operation:v0.2.0
