
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: triggers.diagnosis.kubediag.org
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.operationSet
    name: OperationSet
    type: string
  - JSONPath: .status.ready
    name: Ready
    type: boolean
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: diagnosis.kubediag.org
  names:
    kind: Trigger
    listKind: TriggerList
    plural: triggers
    singular: trigger
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Trigger is the Schema for the triggers API.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TriggerSpec defines the desired state of Trigger.
          properties:
            nodeName:
              description: NodeName is the default node which the diagnosis is on.
              type: string
            operationSet:
              description: OperationSet is the name of referenced operation set in
                the generated diagnosis.
              type: string
            parameters:
              additionalProperties:
                type: string
              description: Parameters is a set of the parameters to be passed to diagnosis.
              type: object
            sourceTemplate:
              description: SourceTemplate is the template of trigger.
              properties:
                commonEventTemplate:
                  description: CommonEventTemplate specifies the template to create
                    a diagnosis from a common event.
                  properties:
                    regexp:
                      description: CommonEventTemplateRegexp is the regular expression
                        for matching common event template. All regular expressions
                        must be in the syntax accepted by RE2 and described at https://golang.org/s/re2syntax.
                      properties:
                        class:
                          description: Class is the regular expression for matching
                            "Class" of common event.
                          type: string
                        component:
                          description: Component is the regular expression for matching
                            "Component" of common event.
                          type: string
                        group:
                          description: Group is the regular expression for matching
                            "Group" of common event.
                          type: string
                        severity:
                          description: Severity is the regular expression for matching
                            "Severity" of common event.
                          type: string
                        source:
                          description: Source is the regular expression for matching
                            "Source" of common event.
                          type: string
                      type: object
                  type: object
                cronTemplate:
                  description: CronTemplate specifies the template to create a diagnosis
                    periodically at fixed times.
                  properties:
                    schedule:
                      description: Schedule is the schedule in cron format. See https://en.wikipedia.org/wiki/Cron
                        for more details.
                      type: string
                  required:
                  - schedule
                  type: object
                kubernetesEventTemplate:
                  description: KubernetesEventTemplate specifies the template to create
                    a diagnosis from a kubernetes event.
                  properties:
                    regexp:
                      description: Regexp is the regular expression for matching kubernetes
                        event template.
                      properties:
                        message:
                          description: Message is the regular expression for matching
                            "Message" of kubernetes event.
                          type: string
                        name:
                          description: Name is the regular expression for matching
                            "Name" of kubernetes event.
                          type: string
                        namespace:
                          description: Namespace is the regular expression for matching
                            "Namespace" of kubernetes event.
                          type: string
                        reason:
                          description: Reason is the regular expression for matching
                            "Reason" of kubernetes event.
                          type: string
                        source:
                          description: Source is the regular expression for matching
                            "Source" of kubernetes event. All fields of "Source" are
                            regular expressions.
                          properties:
                            component:
                              description: Component from which the event is generated.
                              type: string
                            host:
                              description: Node name on which the event is generated.
                              type: string
                          type: object
                      type: object
                  required:
                  - regexp
                  type: object
                prometheusAlertTemplate:
                  description: One and only one of the following source should be
                    specified. PrometheusAlertTemplate specifies the template to create
                    a diagnosis from a prometheus alert.
                  properties:
                    containerReferenceLabel:
                      description: ContainerReferenceLabel specifies the label for
                        setting ".spec.podReference.container" of generated diagnosis.
                        The label value will be set as ".spec.podReference.container"
                        field.
                      type: string
                    nodeNameReferenceLabel:
                      description: NodeNameReferenceLabel specifies the label for
                        setting ".spec.nodeName" of generated diagnosis. The label
                        value will be set as ".spec.nodeName" field.
                      type: string
                    parameterInjectionLabels:
                      description: ParameterInjectionLabels specifies the labels for
                        setting ".spec.parameters" of generated diagnosis. All label
                        names and values will be set as key value pairs in ".spec.parameters"
                        field.
                      items:
                        description: A LabelName is a key for a LabelSet or Metric.  It
                          has a value associated therewith.
                        type: string
                      type: array
                    podNameReferenceLabel:
                      description: PodNameReferenceLabel specifies the label for setting
                        ".spec.podReference.name" of generated diagnosis. The label
                        value will be set as ".spec.podReference.name" field.
                      type: string
                    podNamespaceReferenceLabel:
                      description: PodNamespaceReferenceLabel specifies the label
                        for setting ".spec.podReference.namespace" of generated diagnosis.
                        The label value will be set as ".spec.podReference.namespace"
                        field.
                      type: string
                    regexp:
                      description: Regexp is the regular expression for matching prometheus
                        alert template.
                      properties:
                        alertName:
                          description: AlertName is the regular expression for matching
                            "AlertName" of prometheus alert.
                          type: string
                        annotations:
                          additionalProperties:
                            description: A LabelValue is an associated value for a
                              LabelName.
                            type: string
                          description: Annotations is the regular expression for matching
                            "Annotations" of prometheus alert. Only annotation values
                            are regular expressions while all annotation names must
                            be identical to the prometheus alert annotation names.
                          type: object
                        endsAt:
                          description: EndsAt is the regular expression for matching
                            "EndsAt" of prometheus alert.
                          type: string
                        generatorURL:
                          description: GeneratorURL is the regular expression for
                            matching "GeneratorURL" of prometheus alert.
                          type: string
                        labels:
                          additionalProperties:
                            description: A LabelValue is an associated value for a
                              LabelName.
                            type: string
                          description: Labels is the regular expression for matching
                            "Labels" of prometheus alert. Only label values are regular
                            expressions while all label names must be identical to
                            the prometheus alert label names.
                          type: object
                        startsAt:
                          description: StartsAt is the regular expression for matching
                            "StartsAt" of prometheus alert.
                          type: string
                      type: object
                  required:
                  - regexp
                  type: object
              type: object
          required:
          - operationSet
          - sourceTemplate
          type: object
        status:
          description: TriggerStatus defines the observed state of Trigger.
          properties:
            lastScheduleTime:
              description: LastScheduleTime is the last time the cron was successfully
                scheduled.
              format: date-time
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
